module.exports = {
    FB_PAGE_TOKEN: 	'EAAQZAHgbYIacBAFj4mG57iZBUK2KGF62ZCZBbUYyZBhZAETBcZAePRvtGtZCgj3X9G42ttlHH67oAZANTWmQkxblCuhs46kZCfgyHxopZBuRz8MoobSAZBdV0VUbaTV1tyMskYjp1439ckyZAqpVckjwyzrt9ZA9p7Smip6bSqxSrtHvUwLgZDZD',
    FB_PAGE_ID: 'YOUR_FACEBOOK_PAGE_ID',
    FB_VERIFY_TOKEN: 'YOUR_FACEBOOK_VERIFY_TOKEN',
    WIT_TOKEN: '7BARRDG7SAU47FCBLRRX6WLB4EOATNJ7',
};
